---
version:     0.0.1
title:       Advanced Git Recipes
creator:     Arjan van der Gaag
language:    en
publisher:   Untitled publisher
subject:     No subject
description: No description
rights:      Creative Commons BY-SA 3.0 License.
toc:         true
cover_image: cover.png
ignore:
  - README.md
  - outline.md
